name: Exécuter les scripts et envoyer un email

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install --upgrade pip

    - name: Train, test and Val Model
      run: |
        python script/train_evalute_model.py
        python script/test_evalute_model.py
        python script/val_evalute_model.py

    - name: Deploy Model
      run: |
        python script/deploy_model.py

    - name: Send Email
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        python script/send_email.py
