name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install tensorflow seaborn pydoc

    - name: Train and Validate Model
      run: |
        python script/train_model.py
        python script/validate_model.py

    - name: Generate Documentation
      run: |
        pydoc -w script
      continue-on-error: true

    - name: Deploy Model
      run: |
        python script/deploy_model.py

    - name: Send Email
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: |
        python script/send_email.py
